services:
  postgres:
    image: postgres:15
    container_name: clinic-postgres
    environment:
      POSTGRES_DB: clinic_booking_db
      POSTGRES_USER: clinic_user
      POSTGRES_PASSWORD: clinic_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
